export const GolfAttributes = [
    {
        id: 0,
        region: 'Auvergne-Rhône-Alpes',
        name: 'Grand Lyon Chassieu',
        img: `Bluegreen/Golfs/0.jpg`,
    },
    {
        id: 1,
        region: 'Auvergne-Rhône-Alpes',
        name: 'Saint-Etienne',
        img: `Bluegreen/Golfs/1.jpg`,
    },
    {
        id: 2,
        region: 'Auvergne-Rhône-Alpes',
        name: 'Grenoble-Seyssins',
        img: `Bluegreen/Golfs/2.jpg`,
    },
    {
        id: 3,
        region: 'Auvergne-Rhône-Alpes',
        name: 'Grenoble-Bresson',
        img: `Bluegreen/Golfs/3.jpg`,
    },
    {
        id: 4,
        region: 'Bourgogne-Franche-Comté',
        name: 'Val d\'Amour',
        img: `Bluegreen/Golfs/4.jpg`,
    },
    {
        id: 5,
        region: 'Bourgogne-Franche-Comté',
        name: 'Quétigny',
        img: `Bluegreen/Golfs/5.jpg`,
    },
    {
        id: 6,
        region: 'Bretagne',
        name: 'Pléneuf-Val-André',
        img: `Bluegreen/Golfs/6.jpg`,
    },
    {
        id: 7,
        region: 'Bretagne',
        name: 'Lac au Duc Ploërmel',
        img: `Bluegreen/Golfs/7.jpg`,
    },
    {
        id: 8,
        region: 'Bretagne',
        name: 'l\'Odet',
        img: `Bluegreen/Golfs/8.jpg`,
    },
    {
        id: 9,
        region: 'Bretagne',
        name: 'Baden',
        img: `Bluegreen/Golfs/9.jpg`,
    },
    {
        id: 10,
        region: 'Bretagne',
        name: 'Rhuys-Kerver',
        img: `Bluegreen/Golfs/10.jpg`,
    },
     {
        id: 11,
        region: 'Bretagne',
        name: 'Val Queven',
        img: `Bluegreen/Golfs/11.jpg`,
    },
    {
        id: 12,
        region: 'Bretagne',
        name: 'Ploemeur Océan',
        img: `Bluegreen/Golfs/12.jpg`,
    },
    {
        id: 13,
        region: 'Bretagne',
        name: 'Rennes Saint-Jacques',
        img: `Bluegreen/Golfs/13.jpg`,
    },
    {
        id: 14,
        region: 'Bretagne',
        name: 'Saint-Laurent',
        img: `Bluegreen/Golfs/14.jpg`,
    },
    {
        id: 15,
        region: 'Hauts-de-France',
        name: 'l\'Ailette',
        img: `Bluegreen/Golfs/15.jpg`,
    },
    {
        id: 16,
        region: 'Hauts-de-France',
        name: 'Dunkerque',
        img: `Bluegreen/Golfs/16.jpg`,
    },
    {
        id: 17,
        region: 'Centre-Val-de-Loire',
        name: 'Tours Ardrée',
        img: `Bluegreen/Golfs/17.jpg`,
    },
    {
        id: 18,
        region: 'Ile de France',
        name: 'Rueil-Malmaison',
        img: `Bluegreen/Golfs/18.jpg`,
    },
    {
        id: 19,
        region: 'Ile de France',
        name: 'Bellefontaine',
        img: `Bluegreen/Golfs/19.jpg`,
    },
    {
        id: 20,
        region: 'Ile de France',
        name: 'Villenes-sur-Seine',
        img: `Bluegreen/Golfs/20.jpg`,
    },
    {
        id: 21,
        region: 'Ile de France',
        name: 'Saint-Aubin',
        img: `Bluegreen/Golfs/21.jpg`,
    },
    {
        id: 22,
        region: 'Ile de France',
        name: 'Guerville',
        img: `Bluegreen/Golfs/22.jpg`,
    },
    {
        id: 23,
        region: 'Ile de France',
        name: 'Saint-Quentin-en-Yvelines',
        img: `Bluegreen/Golfs/23.jpg`,
    },
    {
        id: 24,
        region: 'Ile de France',
        name: 'Marolles-en-Brie',
        img: `Bluegreen/Golfs/24.jpg`,
    },
    {
        id: 25,
        region: 'Normandie',
        name: 'Houlgate',
        img: `Bluegreen/Golfs/25.jpg`,
    },
    {
        id: 26,
        region: 'Nouvelle-Aquitaine',
        name: 'Niort-Romagné',
        img: `Bluegreen/Golfs/26.jpg`,
    },
    {
        id: 27,
        region: 'Nouvelle-Aquitaine',
        name: 'Domaine des Forges',
        img: `Bluegreen/Golfs/27.jpg`,
    },
    {
        id: 28,
        region: 'Nouvelle-Aquitaine',
        name: 'Gujan-Mestras',
        img: `Bluegreen/Golfs/28.jpg`,
    },
    {
        id: 29,
        region: 'Nouvelle-Aquitaine',
        name: 'Mazières-en-Gâtine',
        img: `Bluegreen/Golfs/29.jpg`,
    },
    {
        id: 30,
        region: 'Nouvelle-Aquitaine',
        name: 'Pessac',
        img: `Bluegreen/Golfs/30.jpg`,
    },
    {
        id: 31,
        region: 'Nouvelle-Aquitaine',
        name: 'Rochefort Océan',
        img: `Bluegreen/Golfs/31.jpg`,
    },
    {
        id: 32,
        region: 'Nouvelle-Aquitaine',
        name: 'Lacanau-La-Méjanne',
        img: `Bluegreen/Golfs/32.jpg`,
    },
    {
        id: 33,
        region: 'Nouvelle-Aquitaine',
        name: 'Bordeaux-Lac',
        img: `Bluegreen/Golfs/33.jpg`,
    },
     {
        id: 34,
        region: 'Nouvelle-Aquitaine',
        name: 'Pau-Artiguelouve',
        img: `Bluegreen/Golfs/34.jpg`,
    },
    {
        id: 35,
        region: 'Occitanie',
        name: 'Grand Rodez',
        img: `Bluegreen/Golfs/35.jpg`,
    },
    {
        id: 36,
        region: 'Pays de la Loire',
        name: 'Savenay',
        img: `Bluegreen/Golfs/36.jpg`,
    },
    {
        id: 37,
        region: 'Pays de la Loire',
        name: 'Le Croisic',
        img: `Bluegreen/Golfs/37.jpg`,
    },
    {
        id: 38,
        region: 'Pays de la Loire',
        name: 'La Domangère',
        img: `Bluegreen/Golfs/38.jpg`,
    },
    {
        id: 39,
        region: 'Pays de la Loire',
        name: 'Avrillé',
        img: `Bluegreen/Golfs/39.jpg`,
    },
    {
        id: 40,
        region: 'Pays de la Loire',
        name: 'Nantes-Erdre',
        img: `Bluegreen/Golfs/40.jpg`,
    },
    {
        id: 41,
        region: 'Pays de la Loire',
        name: 'Pornic',
        img: `Bluegreen/Golfs/41.jpg`,
    },
    {
        id: 42,
        region: 'Pays de la Loire',
        name: 'Pays de Saint Gilles Croix de Vie',
        img: `Bluegreen/Golfs/42.jpg`,
    },
    {
        id: 43,
        region: 'Provence Alpes-côte d’Azur',
        name: 'Sainte-Maxime',
        img: `Bluegreen/Golfs/43.jpg`,
    },
    {
        id: 44,
        region: 'Provence Alpes-côte d’Azur',
        name: 'l\'Estérel',
        img: `Bluegreen/Golfs/44.jpg`,
    },
    {
        id: 45,
        region: 'Provence Alpes-côte d’Azur',
        name: 'Académie de l\'Estérel',
        img: `Bluegreen/Golfs/45.jpg`,
    },
 
];